/**
 * Types of documents that can be generated by the application
 */
export const DOCUMENT_TYPES = {
  TARGET_MARKET_AUDIENCE: 'targetMarketAudience',
  BUSINESS_PROFILE: 'businessProfile',
  STYLE_GUIDE: 'styleGuide'
};

/**
 * Display names for document types
 */
export const DOCUMENT_TYPE_NAMES = {
  [DOCUMENT_TYPES.TARGET_MARKET_AUDIENCE]: 'Target Market Audience Profile',
  [DOCUMENT_TYPES.BUSINESS_PROFILE]: 'Business Dimensional Profile',
  [DOCUMENT_TYPES.STYLE_GUIDE]: 'AI Style Guide'
};

/**
 * Icons for document types (can be replaced with actual icon components)
 */
export const DOCUMENT_TYPE_ICONS = {
  [DOCUMENT_TYPES.TARGET_MARKET_AUDIENCE]: '📊',
  [DOCUMENT_TYPES.BUSINESS_PROFILE]: '📈',
  [DOCUMENT_TYPES.STYLE_GUIDE]: '📝'
};

/**
 * Descriptions for document types
 */
export const DOCUMENT_TYPE_DESCRIPTIONS = {
  [DOCUMENT_TYPES.TARGET_MARKET_AUDIENCE]: 'Comprehensive analysis of your ideal customer segments for semantically calibrating AI systems to accurately understand and target your specific audience demographics, psychographics, behaviors, and needs.',
  [DOCUMENT_TYPES.BUSINESS_PROFILE]: 'Detailed business context document that enables AI systems to generate outputs precisely aligned with your unique business model, market position, offerings, and strategic objectives.',
  [DOCUMENT_TYPES.STYLE_GUIDE]: 'Advanced AI calibration document for consistently aligning AI-generated content with your brand voice, terminology preferences, and communication standards across all platforms.'
};

/**
 * Recommended users for document types
 */
export const DOCUMENT_TYPE_RECOMMENDED_FOR = {
  [DOCUMENT_TYPES.TARGET_MARKET_AUDIENCE]: 'Marketing teams working with AI, digital marketers using LLMs, customer insight specialists',
  [DOCUMENT_TYPES.BUSINESS_PROFILE]: 'AI implementation teams, business strategists leveraging AI tools, consultants optimizing AI workflows',
  [DOCUMENT_TYPES.STYLE_GUIDE]: 'Content teams using generative AI, brand managers implementing AI assistants, AI prompt engineers'
};